version: '3.8'

services:
  food_delivery_db:
    image: mysql:8.0
    container_name: food_delivery_db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: food_delivery_app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - food_delivery_network

  food_delivery_app:
    build:
      context: ./food_delivery_app
      dockerfile: Dockerfile
    container_name: food_delivery_app
    ports:
      - "5454:5454"
    depends_on:
      - food_delivery_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://food_delivery_db:3306/food_delivery_app
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
    networks:
      - food_delivery_network

volumes:
  mysql_data:

networks:
  food_delivery_network:
    driver: bridge 