services:
  db:
    image: mysql:8.0
    container_name: food_delivery_db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: food_delivery_app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - food_delivery_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: food_delivery_app
    ports:
      - "5454:5454"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://food_delivery_db:3306/food_delivery_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    depends_on:
      db:
        condition: service_healthy
    networks:
      - food_delivery_network
    restart: on-failure

networks:
  food_delivery_network:
    external: true

volumes:
  db_data:
